sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        rFiKteXLdThWAiMI7XvckJQ5rskI/1ZdN7kTPpwWSwZEWr+NadM6ADKZxRwT+0wap8NGWYUyvzeUCe0F9/8Fy/Jz1jBvK7kJCG9GAKbmNXGGVUAHYo02RDnli/NWqDIzCBGIoGcd8hYf674JVaG1tEgGBV+vfe8dGep9vM/j/VxiePMTDOxP2BYwDchycviMX14myiGw6JMnvYNgEYsKRN9Oje5m99WDaExysFphBX9mBEB1lCMOGlcbE5Lc2fCsTgLg1LJu+3pMy9OlXiPVtDgk0PNDyU3S/0hdATeGziqdIzO9l3H9tNXeWhzwvLAN0Rdmsw9nRohR+/UMGH3hdOHBsTsiBV4R/2OEYa4DQJtsVQkY+a1tL1fdDdcoi7QlcEfr24uefi2rKM6mHML6sy5ZI7iN4L5OhTKeAjUc48fqWld7pnaMPPT3sRRX+yyKYwvK+EYvbi59dKi6UtcTfhRTq1SAsCPKURRTJZ20RV2UeSxfhFmY3Wa6hXqNCdqaSc8uFx/uuOMHFRo7fAD62q+TdAoJwfDP3460OCVlgeK4lhQZC3/d8M2dM+eZXeCxKulVDMuN8DfZZMV10FfE2LOoNhhcqI2cv83ihUuqWr3Zz6Wgo1zNpGLuEzjFl1fIxRRQzWfSd+llOduhCGt72b3lGMYlQIWM9KEjQJ1FbUw=
    - secure: >-
        EkJjvckxs/H9Sq1lUZUwCw6n5AcACyLIWR1bBohHch0M8TO7PGY/c4df+4wiCvLVA9PyW2JVY442tTNMNT3EOc/nL6o1n0CouZsHcsCGM0uQDRUglO4NHho0R0zVoQkcO5NTPkKhcd6yA/XbHtWF4j+W+Rgs6SJloOPEpgXr2pmFaj7iRuLlWjIKnK7Ae+pTLipbBkFuHW5GzHfiMXNU8b31uAQw0MI5MkbLnuj8BgW5ICfkCnyJQyXUVOV57jCxb7FWv4oQ3FXr3c5xXouKLZ6xvDL+QaVhP4CK4vQg7ws8bVxPuQ7+c1sY6B4oiW/Dmmi1fk3K1xKqVG6oVQ6MxLMckHzCYGi2eVva0UPvaE7pdkMOJ41dE3otLXIdM3QiOE0yAYjO+OidwDCC5cA3k3xVCdiExA4pSB5+q558e5nC7a9QzZxPKVIklpytmagtt2JTgrS474n/bUqlZQa/j0fMtdcsfsj87LRWayCJG1QjcedySiIK9Slyiy7lXw4EEcclYNTz2NB16SRxrqHslTh00QVQkd6Jc4aPMdwa+/rYtoIUBiSujh2ZA+gThCzTBfQKhzFLTsLFc3cvX48phehh1atvqlQGyzCV5FWkC8PdkpwX4cVxpoiAyxNFxSptmhZFQSHNYugyeYwYwBAODrCracQr+8279dtWlk0KcJ0=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
